### ISSUE TITLE
package.josn里缺少request类库的引用声明

### ISSUE THREAD

**Issue by xuming314** [supersheep/wechat-pay#1]
在npm install wechat-pay里下载安装的0.1.0版本，package.json的依赖性没有request声明：
"dependencies": {
    "underscore": "^1.7.0",
    "sha1": "^1.1.0",
    "MD5": "^1.2.1",
    "xml2js": "^0.4.4"
  }
但github里源码的0.1.0版本有。

**Comment by supersheep** [comment]
已更新版本，现在npm上latest为0.1.1
