### ISSUE TITLE
由于微信目前已经更新了。导致签名报错。

### ISSUE THREAD

**Issue by lonso** [supersheep/wechat-pay#12]
现在报签名错误。
{ [ProtocolError: 签名错误] name: 'ProtocolError' }

**Comment by finscn** [comment]
是的 我也遇到了
middleware.js 里 57行左右(我修改过 所以行号不对)

此处 message 里已经显示成功了,  但是 err却是 { [InvalidSignature] name: 'InvalidSignature' }

 payment.validate(rawBody, function(err, message){
        console.log("validate",err,message);

**Comment by finscn** [comment]
看了下腾讯返回的数据,  貌似 支付后校验 不能用 payment.validate

**Comment by finscn** [comment]
支付后返回的  xml里 sign 算法和 支付时用的sign 算法不一样.
<sign><![CDATA[BE6E7D7228C3A062BC3CEB0BEC652812]]></sign>

**Comment by finscn** [comment]
与 #13  提到的问题有关.

**Comment by ityao** [comment]
咋关掉这个问题呢, 我还是遇到这个问题啊
