### ISSUE TITLE
订单信息里有空格时, 为什么会被替换成 + 号?

### ISSUE THREAD

**Issue by finscn** [supersheep/wechat-pay#13]
提交的信息:
attach: 'attach 1 + 2 + 3',

返回的xml:
<attach><![CDATA[attach+1+++2+++3]]></attach>

这个正常吗? 腾讯替换的?

**Comment by finscn** [comment]
会不会是 getRawBody 函数有bug?

**Comment by lonso** [comment]
这个是正常的，是urlencode的问题。以前做银联也遇到过，要把+号 手动转成 空格。

**Comment by lonso** [comment]
var order = {
  body: 'test',
  attach: 'test',
  out_trade_no: 'kfc001',
  total_fee: 100,
  spbill_create_ip: '8.8.8.8',
  openid: 'oAXFPt_Uxzm0TMFicFbjXE8kHKY4',
  trade_type: 'JSAPI'
};

我这个格式都是签名错
