### ISSUE TITLE
用例子都报错啊!

### ISSUE THREAD

**Issue by ityao** [supersheep/wechat-pay#15]
统一下单接口, 直接套用例子, 一直报ProtocolError

**Comment by ityao** [comment]
出来微信服务器返回的是签名错误 return_msg

**Comment by supersheep** [comment]
ProtocolError是在什么阶段报的？支付界面呼出了么？
我这边测试支付界面可以正常呼出，也可以成功支付的。
支付页面的路径放在支付授权目录下了么？

**Comment by shuhankuang** [comment]
{ [ProtocolError: 签名错误] name: 'ProtocolError' }
我也报这个错误。

**Comment by supersheep** [comment]
req.body.IP 是什么样的？可以给出完整项目代码么

**Comment by yijingping** [comment]
@shuhankuang 我的也是啊，报错误：{ [ProtocolError: 签名错误] name: 'ProtocolError' }

**Comment by yijingping** [comment]
纠正一下，作者代码没问题，是我自己的parter_key配置错了

**Comment by shuhankuang** [comment]
@yijingping 我也是parter_key问题，微信的文档太坑了。

**Comment by liguangsong** [comment]
parter_key是什么我的好像也是这里出错了
