### ISSUE TITLE
关于"接收微信付款确认请求"

### ISSUE THREAD

**Issue by finscn** [supersheep/wechat-pay#16]
示例中用的是
```
app.use('<notifyUrl>', ..... );
```

我想问一下 这个地方不用use, 改成 post/get/all 可以吗?  如果不可以 为什么呢?

我的理解是 支付后,  微信会发送请求到  notifyUrl , 我这边只要能接收到这个请求就可以了吧?  为什么要用use和中间件形式呢?  
谢谢

**Comment by supersheep** [comment]
微信过来的应该是post，可以使用post或者all的。
