### ISSUE TITLE
签名错误

### ISSUE THREAD

**Issue by liguangsong** [supersheep/wechat-pay#17]
为什么总报，签名错误，核对了openid

**Comment by supersheep** [comment]
total_fee这个我看了你贴的代码，是因为至少为1，单位是分，你写了0.1 * 1，签名错误不知是否与此相关

**Comment by liguangsong** [comment]
total_fee这个问题我已经改过了，改过之后才报的签名错误，
PaymentController.index = function (req, res) {
    var url = client.getAuthorizeURL('http://1bff2666.ngrok.io/payment/get_open_id', 'hehe', 'snsapi_base');
    res.render('index.ejs', {url: url});
};

PaymentController.get_open_id = function(){

client.getAccessToken(req.query.code, function (err, result) {
    
        var accessToken = result.data.access_token;
        var openid = result.data.openid;
      var order = {
               body: '吮指原味鸡 * 1',
                attach: '{"部位":"三角"}',
                out_trade_no: 'kfc001',
                total_fee:  1,
                spbill_create_ip: ip,
                openid: openid,
                trade_type: 'JSAPI'
            };
payment.getBrandWCPayRequestParams(order, function(err, payargs){
            res.render('pay.ejs',{payargs:payargs});
        
           });
}

var Payment = require('wechat-pay').Payment;
var fs = require('fs');

var initConfig = {
    partnerKey: "商户平台登录密码",
    appId: "公众号APPID",
    mchId: "微信支付商户号",
    notifyUrl: "http://1bff2666.ngrok.io/payment/callback",
    pfx: fs.readFileSync('apiclient_cert.p12')
};
var payment = new Payment(initConfig);


这是我的测试代码你看有什么问题么？微信的测试目录，和网页验证接口添写一直，万分感谢和期待你的回信。

**Comment by liguangsong** [comment]
作者代码没问题，多读读文档就好了

**Comment by vicky8989** [comment]
怎么打印拼接后的支付字符串呢，我现在也是老报protocal error:签名错误，不知道哪里的问题。

**Comment by supersheep** [comment]
主要在 _getSign 方法中，现在node原生支持debug了，用chrome调试工具会比改代码打印更方便。
