### ISSUE TITLE
能否做一个demo,对新手来说这个调用和调试起来还是很困难

### ISSUE THREAD

**Issue by Elegent** [supersheep/wechat-pay#22]
能否用nodejs+express做一个demo

**Comment by luoyjx** [comment]
主要是拼参数，https请求，解析xml

**Comment by supersheep** [comment]
后端写一个ajax接口，使用README当中有生成payargs的例子生成参数，前端使用WeixinJSBridge唤起客户端界面就行。参数生成和回调解析已经都做掉了。调试不在本库的范畴内，可以使用Charles+绑host的方式来做。
