### ISSUE TITLE
为什么总是提示签名错误

### ISSUE THREAD

**Issue by wat2012** [supersheep/wechat-pay#26]
我使用的参数是
var initConfig = {
    partnerKey : "7***_7",
    appId : "wxb7**_****_766216",
    mchId : "1281077801",
    notifyUrl : "http://**_.******.com/payment/notify",
    pfx : fs.readFileSync("apiclient_cert.p12")
};

调用的接口是

```
var order = {
    body : '吮指原味鸡 * 1',
    attach : '{"部位":"三角"}',
    out_trade_no : 'kfc' + (Date.parse(new Date())),
    total_fee : 1,
    spbill_create_ip :  req.ip,
    openid : "otVC4wbMR1nHA6wDu2XG11CSF3fc",
    trade_type : 'JSAPI'
};

payment.getBrandWCPayRequestParams(order, function (err, payargs) {
    if (err) {
        console.log(err);
        res.send(err);
    } else {
        console.log(payargs);
        res.json(payargs);
    }
});
```

提示返回值

![image](https://cloud.githubusercontent.com/assets/2884051/11173189/c90f9bd4-8c4d-11e5-98f9-493d327de2a8.png)

**Comment by superlbr** [comment]
去掉attach呢

**Comment by goofansu** [comment]
检查一下`partnerKey`填对了吗？这个参数是[微信商户后台](http://pay.weixin.qq.com) -> “API安全”里的那个密钥，应该是32位的。

**Comment by qzhao2007** [comment]
这个问题fix了吗？我也总是碰到这个问题

**Comment by superlbr** [comment]
我们用了一年左右，正常

**Comment by wyc0991** [comment]
签名错误 ，你们怎么解决的

**Comment by superlbr** [comment]
有可能是中文编码的问题@wyc0991

**Comment by szwork2013** [comment]
partnerKey最好用md5在线工具生成,否则自己手写的容易出现签名错误。

**Comment by channg** [comment]
可以看下公众号那微信支付路径，如果带＃的url 要吧＃后面路径名耶带上

**Comment by caohongtao** [comment]
我也遇到了这个问题，最终发现是partnerKey的问题。
partnerKey就是微信支付后台的API密钥。
我当初保存的初始的API密钥不知道为什么不对。我就试着重置了一下，问题就解决了。
