### ISSUE TITLE
NATIVE　方式不显示code_url解决方法

### ISSUE THREAD

**Issue by guhaizhous** [supersheep/wechat-pay#3]
在payment.js文件中找到Payment.prototype.getBrandWCPayRequestParams方法

Payment.prototype.getBrandWCPayRequestParams = function (order, callback) {
  var self = this;
  var default_params = {
    appId: this.appId,
    timeStamp: this._generateTimeStamp(),
    nonceStr: this._generateNonceStr(),
    signType: "MD5"
  };

  order = this._extendWithDefault(order, [
    'notify_url'
  ]);

  this.unifiedOrder(order, function (err, data) {
    if (err) {
      return callback(err);
    }

    var params = _.extend(default_params, {
      package: "prepay_id=" + data.prepay_id
    });

    params.paySign = self._getSign(params);
    //=================================
　//这里要加一个判断，如果是NATIVE方式需要显示code_url，
    if(order.trade_type="NATIVE"){
     params.code_url=data.code_url;
    }
   //================================
    callback(null, params);
  });
};

**Comment by supersheep** [comment]
加上了，多谢。以后可以提pull request哈。使用看没有问题的话我发一个新版。
