### ISSUE TITLE
Please release a new version?

### ISSUE THREAD

**Issue by holymonson** [supersheep/wechat-pay#30]
Then we can drag the package with new features from npm, pulling from github behind GFW is very painful. T_T

**Comment by supersheep** [comment]
好，之前因为单侧比较难搞，所以不是很确定达到可以publish的状态了。家里的网出口带宽有点渣，我最晚周一会publish

**Comment by holymonson** [comment]
@supersheep Hi?

**Comment by supersheep** [comment]
@holymonson 好了，抱歉之前忘了
