### ISSUE TITLE
请问在ThinkJS中怎么接收微信支付结果通知

### ISSUE THREAD

**Issue by cos800** [supersheep/wechat-pay#46]
readme示例中好像是基于express框架?

但是我用的是thinkjs框架，支付是成功了，

但是该怎么接收到微信推送的支付结果通知？
```
    async paybackAction() {
        let wxPayCfg = {
            // ....
        };

        middleware(wxPayCfg).getNotify().done((message, req, res, next)=>{
            console.log(message);
        });
    }
```
这样似乎不对。

**Comment by supersheep** [comment]
对ThinkJS不太了解，但express的中间件是一个函数，也就是说 middleware(initConfig).getNotify().done(function(){}) 会返回一个函数，所以你这样写并没有去执行他，当然就不会有效果了。

**Comment by cos800** [comment]
能否加个功能为了兼容express之外的nodejs框架，
比如直接将xml字符串传给wechat-pay，
然后wechat-pay验证通过后返回解析后的数据。

**Comment by supersheep** [comment]
wechat-pay做的事情就是简化配置、生成xml并向微信服务器发送请求，如果自己xml都生成好了，那自己直接往微信发请求就好。有问题可以用微信提供的校验工具排错。
