### ISSUE TITLE
不支持 支付端 是 IPv6 吗?

### ISSUE THREAD

**Issue by finscn** [supersheep/wechat-pay#8]
我这边的对外IP 是 IPv6, 
执行 payment.getBrandWCPayRequestParams 时报错:

req.ip ::ffff:101.226.125.108
pay err   { [ProtocolError: invalid spbill_create_ip] name: 'ProtocolError' }

**Comment by supersheep** [comment]
嗯，这个是微信那边给出的错，看来是这样的。之前自己取出来出现过多个ip（因为有nginx proxy pass），也会报这个错。

**Comment by finscn** [comment]
看来IP只能瞎写了... 其实微信完全没必要验证这个啊 不知道意义何在 唉

**Comment by cnevinc** [comment]
同意 不知道是在填什麼意思的

**Comment by blusewang** [comment]
刚刚遇到了一个IPV6的。
只好把这个参数瞎填了一个。居然真过了！
猫了个咪！
